#!/usr/bin/env python3

from pathlib import Path
import argparse
import subprocess
import sys
import re


ROOT = Path(__file__).resolve().parent.parent
USER_DIR = ROOT / "user"
SRC_DIR = USER_DIR / "src"
BUILD_DIR = USER_DIR / "build"
INCLUDE_DIR = USER_DIR / "include"
LIB_DIR = USER_DIR / "lib"

GENERATED_RS = ROOT / "kernel" / "src" / "loader" / "generated.rs"

ARCH_CONFIG = {
    "riscv64": {
        "gcc": "riscv64-unknown-elf-gcc",
        "objcopy": "riscv64-unknown-elf-objcopy",
        "objdump": "riscv64-unknown-elf-objdump",
        "linker": USER_DIR / "linker-riscv64.ld",
        "runtime": LIB_DIR / "syscall_riscv64.S",
        "crt0": LIB_DIR / "crt0_riscv64.S",
        "runtime": LIB_DIR / "syscall_riscv64.S",
        "cflags": [
            "-march=rv64gc",
            "-mabi=lp64",
            "-mcmodel=medany",
            "-mno-relax",
            "-msmall-data-limit=0",
            "-DUSER_ARCH_RISCV64",
        ],
        "ldflags": [
            "-Wl,--no-relax",
        ],
    },
    "loongarch64": {
        "gcc": "loongarch64-unknown-linux-gnu-gcc",
        "objcopy": "loongarch64-unknown-linux-gnu-objcopy",
        "objdump": "loongarch64-unknown-linux-gnu-objdump",
        "linker": USER_DIR / "linker-loongarch64.ld",
        "runtime": LIB_DIR / "syscall_loongarch64.S",
        "crt0": LIB_DIR / "crt0_loongarch64.S",
        "runtime": LIB_DIR / "syscall_loongarch64.S",
        "cflags": [
            "-DUSER_ARCH_LOONGARCH64",
        ],
        "ldflags": [],
    },
}
def run(cmd):
    print("+", " ".join(str(x) for x in cmd))
    subprocess.run(cmd, check=True)


def sanitize_name(path: Path) -> str:
    name = path.stem
    name = re.sub(r"[^A-Za-z0-9_]", "_", name)
    if name and name[0].isdigit():
        name = "APP_" + name
    return name.upper()


def rust_bytes(data: bytes, indent: str = "    ") -> str:
    lines = []
    for i in range(0, len(data), 12):
        chunk = data[i:i + 12]
        line = indent + ", ".join(f"0x{b:02x}" for b in chunk) + ","
        lines.append(line)
    return "\n".join(lines)


def collect_sources():
    sources = []
    for ext in ("*.S", "*.c"):
        sources.extend(SRC_DIR.glob(ext))
    sources.sort(key=lambda p: p.name)
    return sources


def build_one(arch: str, source: Path, app_id: int):
    cfg = ARCH_CONFIG[arch]

    out_dir = BUILD_DIR / arch
    out_dir.mkdir(parents=True, exist_ok=True)

    stem = source.stem
    obj = out_dir / f"{app_id}_{stem}.o"
    crt0_obj = out_dir / f"{app_id}_{stem}_crt0.o"
    runtime_obj = out_dir / f"{app_id}_{stem}_runtime.o"
    elf = out_dir / f"{app_id}_{stem}.elf"
    bin_path = out_dir / f"{app_id}_{stem}.bin"

    common_flags = [
        "-ffreestanding",
        "-fno-builtin",
        "-fno-stack-protector",
        "-fno-pic",
        "-fno-pie",
        "-nostdlib",
        "-nostartfiles",
        "-static",
        "-I", str(INCLUDE_DIR),
    ]
    run([
        cfg["gcc"],
        *cfg["cflags"],
        *common_flags,
        "-c",
        str(cfg["crt0"]),
        "-o",
        str(crt0_obj),
    ])

    compile_cmd = [
        cfg["gcc"],
        *cfg["cflags"],
        *common_flags,
        "-c",
        str(source),
        "-o",
        str(obj),
    ]
    run(compile_cmd)

  
    runtime_cmd = [
        cfg["gcc"],
        *cfg["cflags"],
        *common_flags,
        "-c",
        str(cfg["runtime"]),
        "-o",
        str(runtime_obj),
    ]
    run(runtime_cmd)

    link_objects = []

    if source.suffix == ".c":
        link_objects.append(str(crt0_obj))

    link_objects.append(str(obj))

    if source.suffix == ".c":
        link_objects.append(str(runtime_obj))
    link_cmd = [
        cfg["gcc"],
        *cfg["cflags"],
        "-nostdlib",
        "-nostartfiles",
        "-static",
        "-no-pie",
        "-Wl,--build-id=none",
        *cfg["ldflags"],
        "-T", str(cfg["linker"]),
        *link_objects,
        "-o",
        str(elf),
    ]
    run(link_cmd)


    objcopy_cmd = [
        cfg["objcopy"],
        "-O", "binary",
        "-j", ".text",
        str(elf),
        str(bin_path),
    ]
    run(objcopy_cmd)

    data = bin_path.read_bytes()
    if not data:
        raise RuntimeError(f"{source} produced empty binary")

    print(f"[user] built app{app_id}: {source.name}, {len(data)} bytes")
    return {
        "id": app_id,
        "source": source,
        "name": source.stem,
        "symbol": sanitize_name(source),
        "bin": bin_path,
        "data": data,
    }


def generate_rs(apps, arch: str):
    GENERATED_RS.parent.mkdir(parents=True, exist_ok=True)

    out = []
    out.append("// This file is auto-generated by user/build.py.")
    out.append("// Do not edit by hand.")
    out.append(f"// arch = {arch}")
    out.append("")
    out.append(f"pub const APP_NUM: usize = {len(apps)};")
    out.append("")

    for app in apps:
        sym = app["symbol"]
        out.append(f"// app {app['id']}: {app['source'].name}, len={len(app['data'])}")
        out.append(f"static {sym}: &[u8] = &[")
        out.append(rust_bytes(app["data"]))
        out.append("];")
        out.append("")

    out.append("static APP_NAMES: [&str; APP_NUM] = [")
    for app in apps:
        out.append(f'    "{app["name"]}",')
    out.append("];")
    out.append("")

    out.append("static APPS: [&[u8]; APP_NUM] = [")
    for app in apps:
        out.append(f"    {app['symbol']},")
    out.append("];")
    out.append("")

    out.append("pub fn get_app_data(app_id: usize) -> &'static [u8] {")
    out.append("    APPS.get(app_id).copied().unwrap_or_else(|| panic!(\"bad app id {}\", app_id))")
    out.append("}")
    out.append("")

    out.append("pub fn get_app_name(app_id: usize) -> &'static str {")
    out.append("    APP_NAMES.get(app_id).copied().unwrap_or_else(|| panic!(\"bad app id {}\", app_id))")
    out.append("}")
    out.append("")

    GENERATED_RS.write_text("\n".join(out), encoding="utf-8")
    print(f"[user] generated {GENERATED_RS}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("arch", choices=ARCH_CONFIG.keys())
    parser.add_argument("--objdump", action="store_true", help="print objdump for each app")
    args = parser.parse_args()

    if not SRC_DIR.exists():
        print(f"missing {SRC_DIR}", file=sys.stderr)
        sys.exit(1)

    sources = collect_sources()
    if not sources:
        print(f"no .S or .c files found in {SRC_DIR}", file=sys.stderr)
        sys.exit(1)

    apps = []
    for app_id, source in enumerate(sources):
        apps.append(build_one(args.arch, source, app_id))

    generate_rs(apps, args.arch)

    if args.objdump:
        cfg = ARCH_CONFIG[args.arch]
        for app in apps:
            elf = BUILD_DIR / args.arch / f"{app['id']}_{app['source'].stem}.elf"
            run([cfg["objdump"], "-d", str(elf)])


if __name__ == "__main__":
    main()